README.md, spec/DependencyInjection/Compiler/KernelPassSpec.php, src/AppCache.php, src/DependencyInjection/Compiler/KernelPass.php, src/Proxy/TagAwareStore.php
> [EZP-26982](https://jira.ez.no/browse/EZP-26982)
Fixes the integration of the package into ezpublish-kernel.
=> Fix kernel integration

composer.json, src/Resources/config/slot.yml, src/SignalSlot/RemoveTranslationSlot.php, tests/SignalSlot/AbstractSlotTest.php, tests/SignalSlot/RemoveTranslationSlotTest.php
Implements [EZP-27713](https://jira.ez.no/browse/EZP-27713)
----
This PR implements HttpCache `RemoveTranslationSlot` for `RemoveTranslationSignal` introduced in ezsystems/ezpublish-kernel#2031.
Similar slot for deprecated EzPublishCoreBundle HttpCache was introduced in ezsystems/ezpublish-kernel#2062.
**TODO**:
=> EZP-27713: As a Developer I want HttpCache to handle RemoveTranslationSignal

composer.json, tests/Proxy/TagAwareStoreTest.php, tests/PurgeClient/FOSPurgeClientTest.php, tests/PurgeClient/LocalPurgeClientTest.php, tests/SignalSlot/AbstractSlotTest.php, tests/SignalSlot/PublishVersionSlotTest.php, tests/SignalSlot/RemoveTranslationSlotTest.php
This PR resolves:
* `phpunit\phpunit` constraint now requires `^5.7`
* all test cases updated to use namespaced `TestCase`
* removed all deprecated `getMock` method calls
* mocks now use PHP class name constants
=> Use PHPUnit v5.7

composer.json
This PR allows `ezpublish-kernel:^7.0@dev` for `ezplatform-http-cache`.
Reason: Right now we have to make workaround to install `ezplatform:2.0` meta-repository dependencies by setting requirement for `ezpublish-kernel` in the form of `7.0.x-dev as 6.99.x-dev` instead of simply `^7.0@dev`. This change solves that partially (see also: ezsystems/ez-support-tools#24).
=> [Composer] Allowed ezpublish-kernel ^7.0

src/Resources/config/slot.yml, src/SignalSlot/CopySubtreeSlot.php, tests/SignalSlot/CopySubtreeSlotTest.php
> JIRA: https://jira.ez.no/browse/EZP-28160
This PR adds a missing HTTP Cache purging after the subtree copying. Discovered while testing https://github.com/ezsystems/PlatformUIBundle/pull/893#issuecomment-340418960
> 1. Create the following structure:
> a) Home/Folder A
> b) Home/Folder A/Folder B
> c) Home/Folder A/Folder B/Article
> 2. Copy subtree Folder B into Folder A
> 3. Copy subtree Folder B into Folder A again
> 4. Go to location view for Folder A
> 5. The pagination is broken (see attached screenshot) because childCount in response to GET /api/ezp/v2/content/location/X/Y is out of date.
=> EZP-28160: Added HTTP Cache purge after copying subtree

src/DependencyInjection/Compiler/KernelPass.php
This bundle relies on `ezplatform.http_cache.purge_client` but the code in ez kernel sets `ezpublish.http_cache.purge_client` 
Wiring has not been done, which also mean, that this feature was not tested.
=> Purge type HTTP just does not work

src/Resources/config/slot.yml
> JIRA: https://jira.ez.no/browse/EZP-28160
https://github.com/ezsystems/ezplatform-http-cache/pull/18 added 
`EzSystems\PlatformHttpCacheBundle\SignalSlot\CopySubtreeSlot`, which should be connected to `LocationService\CopySubtreeSignal` instead of `ContentService\CopySubtreeSignal`. 
_I'm not sure how I've overlooked this while preparing a commit. My fault._
=> EZP-28160: Wrong slot configuration for HTTP cache purge after copying subtree

spec/EventSubscriber/XLocationIdResponseSubscriberSpec.php, src/DependencyInjection/EzSystemsPlatformHttpCacheExtension.php, src/EventSubscriber/XLocationIdResponseSubscriber.php, src/Proxy/TagAwareStore.php, src/Resources/config/default_settings.yml, src/Resources/config/fos_http_cache.yml, src/Resources/config/view_cache.yml
> Issue: https://jira.ez.no/browse/EZP-28183
>     REST request are not properly tagged and hence not purged as they should, custom controllers not using ContentView is also affected.
> Replaces #21 
@bdunogier @Plopix : Here is somewhat what I had in mind here to begin with. This approach does not need to use response tagger in a way it was made for, and does not need to force caching of all REST responses. It just does one thing, transform the old value to the new one, on top of that it triggers deprecation warning pointing to doc we will need to write on how to deal with tags... (:
Todo:
- _(separate pr)_ Doc on using tags
=> EZP-28183: Requests (incl from REST) with X-Location-Id not tagged

README.md
according to https://httpd.apache.org/docs/2.4/mod/mod_env.html there should be no equals sign when defining an Env Variable
=> Fixed SetEnv syntax in README.md

.gitignore, .php_cs, .travis.yml, composer.json, src/AppCache.php, src/DependencyInjection/Compiler/KernelPass.php, src/DependencyInjection/EzSystemsPlatformHttpCacheExtension.php, src/EventSubscriber/XLocationIdResponseSubscriber.php, tests/Proxy/TagAwareStoreTest.php, tests/SignalSlot/CopySubtreeSlotTest.php
This PR introduces `.php_cs` config and aligns CS.
To simplify fixing code it adds dev dependency on `php-cs-fixer` and introduces composer command:
```
composer fix-cs
```
which runs fixer on all files.
**TODO**:
=> EZP-28161: Enable php-cs-fixer aligned with v2.7.1 settings

spec/DependencyInjection/Compiler/KernelPassSpec.php, spec/EventSubscriber/XLocationIdResponseSubscriberSpec.php, spec/ResponseConfigurator/ConfigurableResponseCacheConfiguratorSpec.php, src/DependencyInjection/Compiler/KernelPass.php, src/EventSubscriber/XLocationIdResponseSubscriber.php, src/Handler/TagHandler.php, src/Handler/TagHandlerInterface.php, src/Resources/config/services.yml, src/Resources/config/view_cache.yml, src/ResponseConfigurator/ConfigurableResponseCacheConfigurator.php
So, instead of dealing with xkeys in both XLocationIdResponseSubscriber and ConfigurableResponseCacheConfigurator I created a interface for it, TagHandlerInterface. Not 100% happy with then name as it might be confusing as FOS also have a TagHandler.
=> Definded handling of tag header in a separate TagHandlerInterface

spec/DependencyInjection/Compiler/KernelPassSpec.php, src/DependencyInjection/Compiler/KernelPass.php
It might be needed for 3rd party drivers to acquire the purge_type setting. With this new parameter you may get it without depending on kernel
=> Exposing ezplatform.http_cache.purge_type parameter for 3rd party drivers

src/AppCache.php
Like in https://github.com/ezsystems/ezplatform/pull/216, make sure to:
- mark response as private when varying on X-User-Hash
Also align with Varnish by doing the following when **not** in debug mode:
- Remove xkey headers
- Remove X-User-Hash vary by header
- Also remove the Symfony Proxy specific x-content-digest header
NOTE:
- I'm somewhat uncomfortable having this logic here and not expose ways to configure it like you can with VCL, this is why I defined it in own method so end user can overload it.
- Also could perhaps better make it clear how you can see the raw response, maybe have a `X-Debug-Hint` header saying you can enable kernel debug to get the raw backend response headers, but also a bit strange to have this in prod.
=> EZP-28126: Align AppCache with Varnish behaviour

spec/EventSubscriber/XLocationIdResponseSubscriberSpec.php, src/EventSubscriber/XLocationIdResponseSubscriber.php, src/Resources/config/view_cache.yml
> issue: https://jira.ez.no/browse/EZP-28326
With this bundle, REST HttpCache is not cleared when moving content,
editing content types, (...) And given the time it will take to fix
REST server to return data that can be used for ResponseTaggers and
how this also affects custum responses given, as we now only purge
by specific tags. Adding this is thus safests.
This somewhat brings back what @Plopix suggested in #21, essentially making sure we
add all tags also to X-Location responses by loading location, but to be on the safe
side it does it using sudo() and catching NotFound. Opted not to reuse ReponseTaggers
here as they don't fully fit, and as we want to rewrite this header independently of
if view cache is enabled or not.
cc @mnocon
=> EZP-28326: Http Cache not updated when moving content on Varnish & Symfony Proxy

src/SignalSlot/MoveSubtreeSlot.php, src/SignalSlot/SwapLocationSlot.php, src/SignalSlot/UpdateLocationSlot.php, tests/SignalSlot/CreateLocationSlotTest.php, tests/SignalSlot/MoveSubtreeSlotTest.php, tests/SignalSlot/SwapLocationSlotTest.php
> Issue: https://jira.ez.no/browse/EZP-28326
Makes it possible to now expire parent location as well as sibling cache for
affected content.
Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2169
Todo:
=> EZP-28326: Use improved signals with parent id's to clear relevant cache

docs/extensibility.md, src/DependencyInjection/ConfigResolver/HttpCacheConfigParser.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/EzPlatformHttpCacheExtension.php, src/EzSystemsPlatformHttpCacheBundle.php
Moves the `http_cache` semantic configuration defined by `ezsystems/ezpublish-kernel` to this package. The semantic configuration added by the kernel gets overridden when defined in this package, and the processing of the configuration is done by both the kernel and this package.
This is done by making the `http cache` semantic config extensible by adding ConfigParsers to it instead of the kernel. See [the documentation](https://github.com/ezsystems/ezplatform-http-cache/tree/migrate_configuration/docs/extensibility.md).
=> Migrated http_cache configuration from kernel

.travis.yml, src/AppCache.php, src/Proxy/UserContextSubscriber.php
Another thing needed for https://github.com/ezsystems/ezpublish-kernel/pull/2194
Look into if we could already reuse more of FosHttpCache here _(for instance it's getDefaultSubscribers Purge & Refresh Subscriber, as commented on inline here now)_, however that won't be possible before we move to FosHttpCache 2.x.
=> Move UserContextSubscriber logic to ezplatform-http-cache

src/Handler/TagHandler.php, src/Proxy/TagAwareStore.php
> [EZP-28760](https://jira.ez.no/browse/EZP-28760) Varnish xkey header using wrong separator
Header seems to be transformed to comma separated values per [rfc2616](https://tools.ietf.org/html/rfc2616#section-4.2)
by potentially Apache &/or others _(not seen this happen on nginx)_.
As Varnish xkey now has doc stating space separated header is supported,
change to rather use that to stay on the safe side of this.
=> EZP-28760: Change to use space seperated header

docs/using_tags.md, src/Handler/TagHandler.php, src/Resources/config/fos_http_cache.yml, src/ResponseConfigurator/ResponseCacheConfigurator.php
Enable usage of [fos_httpcache_tag()](http://foshttpcachebundle.readthedocs.io/en/1.3/features/tagging.html#tagging-from-twig-templates) and FOS TagHandler in order to be able to solve tagging relations which is template logic, added doc on how.
Todo:
Followup:
- PR on overloading template output to tag responses _(as kernel is meant to know nothing of http cache)_
=> EZP-28848: Enable using FOSHttpCache for tagging responses

.travis.yml, composer.json
0.4 does not work on 2.1 as the changes for that is part of 0.5, so
adjusts both composer and travis to reflect that.
Side: This might fail for unrelated reason on PHP 5.6 with 1.13, if
so then we know for sure #58 is not causing it's failues.
=> [0.4] Ajust composer and travis prior to 2.1 release

src/PurgeClient/VarnishPurgeClient.php, tests/PurgeClient/VarnishPurgeClientTest.php
Found when reviewing code for another issue atm, now that purgeAll() is
supposed to work by invalidating a tag, it should use PURGE _(using
invalidatePath() like code above)_, and not BAN _(as used by invalidate())_.
=> [Varnish] Use PURGE for purgeAll()

src/DependencyInjection/Compiler/HttpCachePass.php, src/EzSystemsPlatformHttpCacheBundle.php
JIRA issue: https://jira.ez.no/browse/EZP-28993
This PR backports `HttpCachePass` removed in https://github.com/ezsystems/ezpublish-kernel/pull/2194/files#diff-469a42b65cf73f41f143b52df89d1e70
=> EZP-28993: Varnish cache is not updated after modifying Content

composer.json, src/Resources/config/slot.yml, src/SignalSlot/UpdateUrlSlot.php, tests/SignalSlot/UpdateUrlSlotTest.php
> JIRA: https://jira.ez.no/browse/EZP-28585
> Requires: https://github.com/ezsystems/ezpublish-kernel/pull/2259
Implementation of HTTP cache purge when `URLService\UpdateURLSignal` is emitted. Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2259
=> EZP-28580: HTTP Cache purge when URLService\UpdateURLSignal is emitted

composer.json, src/Resources/config/fos_http_cache.yml
Requires and Description: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/434
=> Fix: AnonymousRequestMatcher doesn't check session name prefix

composer.json, spec/EventSubscriber/HiddenLocationExceptionSubscriberSpec.php, src/EventSubscriber/HiddenLocationExceptionSubscriber.php, src/Resources/config/view_cache.yml
| **JIRA issue**     | [EZP-29297](https://jira.ez.no/browse/EZP-29297)
| **Bug**| yes
| **New feature**    | no
| **Target version** | master (`0.7`)
| **Tests pass**     | yes/no
These changes are related to: https://github.com/ezsystems/ezpublish-kernel/pull/2350
=> EZP-29297: 404 error pages for hidden locations should be tagged

spec/EventSubscriber/HttpCacheResponseSubscriberSpec.php, src/EventSubscriber/HttpCacheResponseSubscriber.php
This PR contain missing piece of changes introduced in https://github.com/ezsystems/ezplatform-http-cache/pull/70.
=> Missing tagger refactoring in HttpCacheResponseSubscriber

docs/varnish/vcl/parameters.vcl, docs/varnish/vcl/varnish4.vcl, src/DependencyInjection/ConfigResolver/HttpCacheConfigParser.php, src/PurgeClient/VarnishPurgeClient.php, src/Resources/config/services.yml, tests/PurgeClient/VarnishPurgeClientTest.php
Meta repo changes:
default_parameters.yml
```
varnish_invalidate_token: '%env(HTTPCACHE_VARNISH_INVALIDATE_TOKEN)%'
env(HTTPCACHE_VARNISH_INVALIDATE_TOKEN): ~
```
ezplatform.yml
```
ezpublish:
...
system:
...
site_group: (same for admin_group)
http_cache:
purge_servers: ['%purge_server%']
+             			varnish_invalidate_token: '%varnish_invalidate_token%'
```
.env
```
#HTTPCACHE_VARNISH_INVALIDATE_TOKEN=""
```
https://jira.ez.no/browse/EZP-29817
=> EZP-29817: Varnish - Purge requests with tokens

composer.json, spec/Handler/TagHandlerSpec.php, src/EventSubscriber/UserContextSubscriber.php, src/Handler/TagHandler.php, src/PurgeClient/PurgeClientInterface.php, src/PurgeClient/RepositoryPrefixDecorator.php, src/PurgeClient/VarnishPurgeClient.php, src/Resources/config/services.yml, src/Resources/config/view_cache.yml, tests/PurgeClient/RepositoryPrefixDecoratorTest.php
Issue: https://jira.ez.no/browse/EZP-29194
Followup to fix the following edge cases:
* Prefix tag for user context hash, so it can be correctly purged when repo prefixes er in use
* Always tag responses with unprefixed `ez-all`, as this is used in `purgeAll()` on Varnish and Fastly. Makes sure `purgeAll()` works the same in all Proxies; clearing _all_ cache across all repositories.
* Note: To clear all cache but only for a specific repo, use _(`purge(['ez-all'])`)_ or from command line using fos command to clear by `ez-all` tag, these calls will/should be prefixed.
Follow up on this is to add a optional cache clearer for symfony that takes advantage of the fixes in purgeAll() to call that when user is calling `bin/console cache:clear`
=> EZP-29194: Improve repo prefix handling for purgeAll() and user context hash tagging

docs/varnish/README.md, docs/varnish/vcl/varnish5.vcl
Story: https://jira.ez.no/browse/EZP-30170
Needed for https://github.com/ezsystems/ezplatform/pull/349
=> EZP-30170: [VCL] Add own VCL for 2.5LTS to bump Varnish support there

src/ProxyClient/Varnish.php, src/PurgeClient/VarnishPurgeClient.php, src/Resources/config/services.yml, tests/PurgeClient/VarnishPurgeClientTest.php
Our [default routes](https://github.com/ezsystems/ezplatform/blob/master/.platform/routes.yaml) on Platform.sh only have https. So in order to send purge requests on Platform.sh, we need to support sending purge requests via HTTPS
=> Allow https scheme for ProxyClient

docs/varnish/vcl/varnish4.vcl, docs/varnish/vcl/varnish5.vcl, src/Controller/InvalidateTokenController.php, src/DependencyInjection/Compiler/HttpCachePass.php, src/EventListener/ConditionallyRemoveVaryHeaderListener.php, src/PurgeClient/VarnishPurgeClient.php, src/Resources/config/default_settings.yml, src/Resources/config/routing.yml, src/Resources/config/services.yml, tests/PurgeClient/VarnishPurgeClientTest.php
This makes it possible for varnish to fetch the purge token from the backend. This is needed on Platform.sh as it is not possible to inject environment variables into varnish container.
With this change we don't need to use environment variables in .vcl so I have removed that part
=> [Cloud feature] Purge token controller

src/DependencyInjection/Compiler/HttpCachePass.php, src/Resources/config/services.yml
Fastly bundle is already changing the fos_http_cache.proxy_client.varnish.class parameter in a [kernelpass](https://github.com/ezsystems/ezplatform-http-cache-fastly/blob/master/src/DependencyInjection/Compiler/KernelPass.php#L19). So when we in ezplatform-http-cache opted to replace the whole parameter with a new one, Fasty's proxyclient was never used
=> Changed how FOS' proxyclient is overriden without breaking fastly bundle

composer.json, src/Resources/config/slot.yml, src/SignalSlot/HideContentSlot.php, src/SignalSlot/RevealContentSlot.php, tests/SignalSlot/AbstractSlotTest.php, tests/SignalSlot/HideContentSlotTest.php, tests/SignalSlot/RevealContentSlotTest.php
> JIRA: https://jira.ez.no/browse/EZP-30358
Implementation of HTTP cache purge when `ContentService\HideContentSignal`/`ContentService\RevealContentSignal` is emitted.
=> EZP-30358: HTTP Cache purge when ContentService\{Hide,Reveal}ContentSignal is emitted

docs/using_tags.md, docs/varnish/README.md, docs/varnish/vcl/varnish4.vcl, docs/varnish/vcl/varnish5.vcl, src/DependencyInjection/ConfigResolver/HttpCacheConfigParser.php, src/PurgeClient/VarnishPurgeClient.php, tests/PurgeClient/VarnishPurgeClientTest.php
| **JIRA issue**     | [EZP-30554](https://jira.ez.no/browse/EZP-30554)
| **Target version** | `0.9`
| **Doc needed**     | _maybe_
As of 2.5LTS we require Varnish 5.1 or higher, meaning we can take advantage of varnish-modules 0.10+ support for [several keys in header while purging](https://github.com/varnish/varnish-modules/blob/master/docs/vmod_xkey.rst#example). In order to:
- Simplify Varnish debugging when checking purge requests
- Reduce rountrips on between web server and varnish for purges
Given the package is also allowed to be used on 1.13, which supports Varnish 4.x. Should we ❓ 
- A. Expose a setting for this as currently is the case in this PR …
=> EZP-30554: Purge several keys at once to simplify debug & reduce round trips

src/Twig/ContentTaggingExtension.php
| **JIRA issue**     | [EZP-30627](https://jira.ez.no/browse//EZP-30627)
| **Target version** |`master` 
| **Doc needed**     | yes
related to https://github.com/ezsystems/ezplatform-admin-ui/pull/1008
**TODO**:
=> EZP-30627: Unified Twig helpers naming

src/DependencyInjection/EzPlatformHttpCacheExtension.php, src/EventSubscriber/UserContextSiteAccessMatchSubscriber.php, src/Resources/config/prepend/ezpublish.yml, src/Resources/config/view_cache.yml, src/Resources/views/fields/content_fields.html.twig
| **JIRA issue**     | [EZP-30544](https://jira.ez.no/browse/EZP-30544)
| **BC breaks**      | yes/no
| **Doc needed**     | yes/no
Related:
https://github.com/ezsystems/ezplatform-http-cache/pull/89 (as this PR contains also this one.)
https://github.com/ezsystems/ezpublish-kernel/pull/2678/files
Relevant Commits:
https://github.com/ezsystems/ezplatform-http-cache/pull/90/commits/fa6e767deeb762de4992a434ea2d6a2b47de32f5
https://github.com/ezsystems/ezplatform-http-cache/pull/90/commits/7dbf6b97e3670c530a54e3f929aa71044e2fda95
**TODO**:
=> EZP-30544: Move cache stuff from Kernel

src/Resources/views/fields/content_fields.html.twig
| **JIRA issue**     | [EZP-30814](https://jira.ez.no/browse/EZP-30814)
Follow up for https://github.com/ezsystems/ezplatform-http-cache/pull/96. Fixed extra `%}` in  content_fields.html.twig. See https://github.com/ezsystems/ezplatform-http-cache/pull/96/files#r311497170
**TODO**:
=> EZP-30814: Fixed extra %} in content_fields.html.twig

src/DependencyInjection/Configuration.php
| **JIRA issue**     | [EZP-30846](https://jira.ez.no/browse/EZP-30846)
Since Symfony 4.3 configuration root name should be passed via constructor instead of using "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method.
More information:
* https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes
* https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config
**TODO**:
=> EZP-30846: Dropped deprecated Symfony\Component\Config\Definition\Builder\TreeBuilder::root method calls

src/AppCache.php, src/DependencyInjection/EzPlatformHttpCacheExtension.php, src/EventSubscriber/UserContextSubscriber.php, src/Resources/config/default_settings.yml, src/Resources/config/fos_http_cache.yml, src/Resources/config/services.yml, src/Resources/config/view_cache.yml
| **JIRA issue**     | [EZP-30544](https://jira.ez.no/browse/EZP-30544)
| **Target version** | `master` for new features
| **Doc needed**     | yes
Instead of relaying on `ezplatform.http_cache.tags.header` default fosCache tags are now used for local and varnish cache. 
**TODO**:
=> EZP-30544: Refactored to use FOSHttpCache default ResponseHeader

src/Resources/views/fields/content_fields.html.twig
| **JIRA issue**     | [EZP-30906](https://jira.ez.no/browse/EZP-30906)
| **Target version** |  `master`
main PR:
https://github.com/ezsystems/ezplatform/pull/453
**TODO**:
=> EZP-30906: Removed deprecated templating component integration

src/ContextProvider/RoleIdentify.php, src/Resources/config/services.yml, tests/ContextProvider/RoleIdentifyTest.php
| **JIRA issue**     | [EZP-30934](https://jira.ez.no/browse/EZP-30934)
| **Target version** |  `master`
**TODO**:
=> EZP-30934: Removed usage of deprecated getCurrentUser method

.travis.yml
| **JIRA issue**     | n/a
| **Type**           | Misc
| **Target version** | 0.8, 0.9, master
Adding Slack notifications to Travis, so that we can setup nightly builds in this repo and avoid detecting issues too late/by accident (like it happened in https://github.com/ezsystems/ezpublish-kernel/pull/2909).
Next step: add nightly builds for 0.8, 0.9 and master
=> [Travis] Added Slack notifications

docs/using_tags.md, src/Handler/ContentTagInterface.php, src/Handler/TagHandler.php, src/Resources/config/view_cache.yml, src/ResponseTagger/Value/ContentInfoTagger.php, src/ResponseTagger/Value/LocationTagger.php, src/Twig/ContentTaggingExtension.php
| **JIRA issue**     | [EZP-31359](https://jira.ez.no/browse/EZP-31359)
| **Type**           | Bug/Improvement
| **Target version** | `0.9` In order to provide future compatibility for page builder and others
| **Doc needed**     | yes, but better if this is done together with the other changes done in 1.0
Exposes abstractions and constants for the content tag prefixes which are the once documented to be used externally.
_NB: I on purpose did not use the new constant in Slots here, I'll adapt 1.0 and the corresponding master branch for that instead, less conflicts._
**TODO**:
=> EZP-31359: Common content http cache tag abstractions

src/PurgeClient/VarnishPurgeClient.php
| **JIRA issue**     | [EZP-30560](https://jira.ez.no/browse/EZP-30560)
| **Target version** | `0.9`
Let's say there is eZ Platform site on Platform.sh. Own domain is used to access the admin. So site has following domains:
- https://project.com for front-end
- https://admin.project.com for admin UI
Front-end (https://project.com) is served by Varnish, but admin is not:
```
// .platform/routes.yaml
https://project.com:
type: upstream
upstream: varnish:http
https://admin.project.com:
type: upstream
upstream: app:http
```
When you edit/publish some content in admin UI (https://admin.project.com), it is expected that its Varnish cache will be …
=> EZP-30560: Unable to clear Varnish cache on Platform.sh

docs/varnish/vcl/varnish5.vcl
| **JIRA issue**     | [EZP-XXXXX](https://jira.ez.no/browse/EZP-XXXXX)
| **BC breaks**      | 🤷‍♂ 
| **Doc needed**     | maybe
Updates VCL to be in sync with the purge logic from FOS.
This drops eZ specific Ban which was Varnish specific, and adds support for FOS capability to do hard tag purge.
=> [3.x][VCL] Update purge logic from FOS

src/EventSubscriber/CachePurge/LocationEventsSubscriber.php, src/EventSubscriber/CachePurge/SectionEventsSubscriber.php
| **JIRA issue**     | [EZP-31113](https://jira.ez.no/browse/EZP-31113)
https://github.com/ezsystems/ezplatform-http-cache/pull/106 for master
**TODO**:
=> EZP-31113: AssignSectionToSubtree event is not handled by search and HTTP cache

src/DependencyInjection/EzPlatformHttpCacheExtension.php, src/Resources/config/services.yml
| **JIRA issue**     | [EZP-31493](https://jira.ez.no/browse/EZP-31493)
| **Type**           | Misc
| **Target version** | `master` for new features
| **Doc needed**     | yes
It seems that based on platform.sh configuration only `varnish` is proper purge_type, so it seems to be better to remove one and stick with `varnish` instead of `http` as it also seems exacly what Fos did.
**TODO**:
=> EZP-31493: Removed http as valid purge type

src/DependencyInjection/EzPlatformHttpCacheExtension.php
| **JIRA issue**     | Follow up to [EZP-31493](https://jira.ez.no/browse/EZP-31493) (#120)
While `http` purge type is no longer needed for Varnish, #120 also removed overriding FOS Sf Container parameters for `local` purge type. It is still default purge type available for any environment other than dev. The following FOSHttpCache parameters were restored:
- `fos_http_cache.tag_handler.response_header`
- `fos_http_cache.tag_handler.separator`
I've discovered this issue while debugging [REST failure](https://travis-ci.org/github/ezsystems/ezplatform-rest/jobs/664966144#L1305). Please observe that when meta is …
=> Restored FOS header and separator override for local purge type

README.md, composer.json
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.0.0`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
This PR replaces `ezpublish-kernel` with `ezplatform-kernel` both in composer and some relevant docs.
=> EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel

spec/ResponseConfigurator/ConfigurableResponseCacheConfiguratorSpec.php, src/Resources/config/view_cache.yml, src/ResponseConfigurator/ConfigurableResponseCacheConfigurator.php
| **JIRA issue**     | [EZP-30543](https://jira.ez.no/browse/EZP-30543)
| **Target version** | l`master`
**TODO**:
=> EZP-30543: Removed Dynamic Settings functionality from kernel

README.md
| **JIRA issue**     | N/A
| **Type**           | Misc
| **Target version** | latest stable `1.0` and `2.0` for doc fixes, `master` for new featured doc
| **Doc needed**     | yes
xkey [example](https://github.com/ezsystems/ezplatform-http-cache/blob/v1.0.0/README.md) and [documentation](https://doc.ezplatform.com/en/2.5/guide/http_cache/#available-tags) doesn't seem to reflect [reality](https://github.com/ezsystems/ezplatform-http-cache/blob/v1.0.0/docs/using_tags.md).
* With eZ Platform 2.5.9 using fresh `composer ezplatform-install` and ezsystems/ezplatform-http-cache v1.0.0, for the root, I have `xkey: ez-all c52 l2 ct42 pl1 p1 p2`
* With eZ Platform 3.0.0 using fresh `composer …
=> README.md: update xkey example

tests/ContextProvider/RoleIdentifyTest.php
| **JIRA issue**     | [EZP-30465](https://jira.ez.no/browse/EZP-30465)
| **Target version** | `2.0@dev` for eZ Platform `v3.0.x`
The signature of `PermissionResolver` constructor has been changed via  ezsystems/ezplatform-kernel#44. One test here relied on that. Updated it so it does not, as it's not relevant for the test itself.
**TODO**:
=> EZP-30465: Aligned tests with Permission Resolver changes

spec/ProxyClient/VarnishSpec.php, src/ProxyClient/Varnish.php
| **JIRA issue**     | [EZP-31607](https://jira.ez.no/browse/EZP-31607)
| **Target version** | `2.0`
Prevent attaching X-Invalidate-Token header to Varnish request when http_cache.varnish_invalidate_token parameter is not set or null.
**TODO**:
=> Fix Adding X-Invalidate-Token header only when TOKEN is not null

composer.json, phpunit.xml, tests/PurgeClient/LocalPurgeClientTest.php
| **JIRA issue**     | n/a
| **Type**           | Improvement in tests
| **Target version** | 1.0, needs to be adapted in 2.1 and master (1)
Failing build: https://travis-ci.org/github/ezsystems/ezplatform-http-cache/jobs/725689032
```
1) eZ\Publish\Core\MVC\Symfony\Cache\Tests\LocalPurgeClientTest::testPurge
Expectation failed for method name is equal to 'purgeByRequest' when invoked 1 time(s)
Parameter 0 for invocation EzSystems\PlatformHttpCacheBundle\RequestAwarePurger::purgeByRequest(Symfony\Component\HttpFoundation\Request Object (...)) does not match expected value.
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
'SCRIPT_NAME' => '' …
```
=> [Tests] Added ClockMock to make time-sensitive tests more robust

src/Twig/ContentTaggingExtension.php
| **JIRA issue**     | EZP-XXXXX
| **Target version** | 2.1+
| **BC breaks**      | no, rather a BC fix depending on how you look at it
| **Doc needed**     | no, doc is already correct if this is merged
Fixing name break in 3.0, as both doc, and the other methods have different syntax by now I suggest we simply close this in the following way, and cleanup when moving to new prefixes at some point in the future. _IMO maybe with a bit better BC next time though._
Reported in: https://github.com/ezsystems/developer-documentation/pull/1132#discussion_r497281925
**TODO**:
=> Fix discrepancy between doc and twig template name

src/Controller/InvalidateTokenController.php
| **JIRA issue**     | [EZP-32020](https://jira.ez.no/browse/EZP-32020)
| **Target version** | `2.1`+
Currently, each request to purge cache by tags triggers a request to "/_ez_http_invalidatetoken" route
A response of this route should be cached by varnish, but it's not.
It's caused by session usage, and the fact this response does not vary by user context.
So, Symfony listener changing response to private.
PS. the same `NO_AUTO_CACHE_CONTROL_HEADER` used in fos symfony cache bundle
**TODO**:
=> EZP-32020: make /_ez_http_invalidatetoken cached by varnish

.travis.yml, behat_suites.yml, features/symfony/cache.feature, features/varnish/cache.feature
| **JIRA issue**     | [EZP-32103](https://issues.ibexa.co/browse/EZP-32103)
| **Type**           | Tests
| **Target version** | 2.1,2.2 and master
Requires: 
1) https://github.com/ezsystems/ezplatform/pull/621
2) https://github.com/ezsystems/BehatBundle/pull/166
Things done:
1) Fixed the test for Symfony cache meant for admin user - without password it was running as anonymous 😅 
2) Added two jobs running tests with Varnish - one with and one without invalidate token
3) Added basic tests for Varnish - making sure that pages are cached for anonymous and logged in users, also that the cache is refreshed correctly on Content changes.
**TODO**:
=> EZP-32103: Add Varnish integration tests

.travis.yml, behat_suites.yml, features/setup/setup.feature, features/symfony/cache.feature, features/symfony/embed.feature, features/symfony/permissions.feature, features/varnish/cache.feature, features/varnish/embed.feature, features/varnish/permissions.feature
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-116
| **Type**           | tests
| **Target version** | 2.3 (Product: 3.3)
Requires:
https://github.com/ezsystems/BehatBundle/pull/182
Added following Scenarios for both Symfony Proxy and Varnish:
1) Permissions: even when a page is cached for Admin the content for Anonymous is correct
2) Embeds: editing an embedded Content Item refreshes the cache for embedding Content item.
3) Embeds: subrequests are cached as well (standard and ESI)
**Before merge:**
Remove TMP commits
**TODO**:
=> IBX-116: More integration tests for HTTP cache

tests/SymfonyProxy/enable_symfony_proxy.patch
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-665
| **Type**           | Misc
| **Target version** | 2.3/master
Symfony 5.3 comes with a new [Runtime component](https://symfony.com/doc/current/components/runtime.html), which changes how the `public/index.php` file looks. This makes the current way of enabling Symfony Proxy invalid, as the patch cannot be applied on the new file and needs to be adapted.
We still need to do three things:
1) Use our own `AppCache` class, as described in https://doc.ibexa.co/en/latest/guide/http_cache/#symfony-reverse-proxy
2) Wrap the Kernel with it: https://symfony.com/doc/current/http_cache.html#symfony-reverse-proxy
3) …
=> IBX-665: Changed how the Symfony Reverse proxy is enabled
